# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1htCG5XXgILLyTFOk7aURe7-3WhDR9wGP
"""

import os
import cv2
import numpy as np
import math
import matplotlib.pyplot as plt

output_dir = './laporan/assets/output'
os.makedirs(output_dir, exist_ok=True)

base_img_lines = cv2.imread('./laporan/assets/cubes.jpeg')
gray_lines = cv2.cvtColor(base_img_lines, cv2.COLOR_BGR2GRAY)
edges_lines = cv2.Canny(gray_lines, 200, 220, apertureSize=3)

def draw_hough_lines(img, lines, color):
    if lines is None:
        return

    for rho, theta in lines[:, 0, :]:
        a = math.cos(theta)
        b = math.sin(theta)
        x0 = a * rho
        y0 = b * rho
        x1 = int(x0 + 1000 * (-b))
        y1 = int(y0 + 1000 * (a))
        x2 = int(x0 - 1000 * (-b))
        y2 = int(y0 - 1000 * (a))
        cv2.line(img, (x1, y1), (x2, y2), color, 2)

def gridtest_hough_lines(
    values,
    detector,
    title,
    file_prefix,
    parameter_name,
    label_text_fn=str,
    label_file_fn=str,
    line_color=(0, 255, 255),
):
    fig, axes = plt.subplots(1, len(values), figsize=(6 * len(values), 6))
    axes = np.atleast_1d(axes)

    for idx, value in enumerate(values):
        img = base_img_lines.copy()
        lines = detector(value)
        draw_hough_lines(img, lines, line_color)

        label_text = label_text_fn(value)
        label_file = label_file_fn(value)
        cv2.imwrite(f'{output_dir}/{file_prefix}_{label_file}.png', img)
        axes[idx].imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        axes[idx].set_title(f'{parameter_name} = {label_text}')
        axes[idx].axis('off')

    plt.suptitle(title, fontsize=14)
    plt.tight_layout()
    plt.savefig(f'{output_dir}/{file_prefix}_grid.png', dpi=200, bbox_inches='tight')
    plt.show()

rho_values = [1, 2, 4]
theta_values = [np.pi / 360, np.pi / 180, np.pi / 90]
threshold_values = [60, 80, 120]
srn_values = [0, 1, 2]
stn_values = [0, 1, 2]

gridtest_hough_lines(
    rho_values,
    lambda rho: cv2.HoughLines(edges_lines, rho, np.pi / 180, 80),
    'Variasi Parameter rho - Hough Lines',
    'hough_lines_rho',
    'rho',
)

gridtest_hough_lines(
    theta_values,
    lambda theta: cv2.HoughLines(edges_lines, 1, theta, 80),
    'Variasi Parameter theta - Hough Lines',
    'hough_lines_theta',
    'theta',
    label_text_fn=lambda value: f'{round(value * 180 / np.pi, 2)}',
    label_file_fn=lambda value: str(round(value * 180 / np.pi, 2)).replace('.', '_'),
)

gridtest_hough_lines(
    threshold_values,
    lambda threshold: cv2.HoughLines(edges_lines, 1, np.pi / 180, threshold),
    'Variasi Parameter threshold - Hough Lines',
    'hough_lines_threshold',
    'threshold',
)

gridtest_hough_lines(
    srn_values,
    lambda srn: cv2.HoughLines(edges_lines, 1, np.pi / 180, 80, srn=srn, stn=0),
    'Variasi Parameter srn - Hough Lines',
    'hough_lines_srn',
    'srn',
)

gridtest_hough_lines(
    stn_values,
    lambda stn: cv2.HoughLines(edges_lines, 1, np.pi / 180, 80, srn=0, stn=stn),
    'Variasi Parameter stn - Hough Lines',
    'hough_lines_stn',
    'stn',
)

"""## Variasi Parameter Hough Lines

Bagian ini menguji pengaruh parameter `theta`, `threshold`, `srn`, dan `stn` pada deteksi garis. Satu cell gridtest menghasilkan beberapa gambar sekaligus dan menyimpan hasil ke `laporan/assets/output`.

## Variasi Parameter Hough Circles

Bagian ini menguji pengaruh `dp`, `minDist`, `param1`, `param2`, `minRadius`, dan `maxRadius` pada deteksi lingkaran. Satu cell gridtest menghasilkan grid hasil per parameter dan menyimpan file ke `laporan/assets/output`.
"""

base_img_circles = cv2.imread('./laporan/assets/citrus.jpeg')
gray_circles = cv2.cvtColor(base_img_circles, cv2.COLOR_BGR2GRAY)
gray_circles = cv2.medianBlur(gray_circles, 11)

def draw_hough_circles(img, circles, outer_color, center_color):
    if circles is None:
        return

    circles = np.uint16(np.around(circles))
    for circle in circles[0, :]:
        cv2.circle(img, (circle[0], circle[1]), circle[2], outer_color, 2)
        cv2.circle(img, (circle[0], circle[1]), 2, center_color, 3)

def gridtest_hough_circles(
    values,
    detector,
    title,
    file_prefix,
    parameter_name,
    label_text_fn=str,
    label_file_fn=str,
    outer_color=(0, 255, 0),
    center_color=(0, 0, 255),
):
    fig, axes = plt.subplots(1, len(values), figsize=(6 * len(values), 6))
    axes = np.atleast_1d(axes)

    for idx, value in enumerate(values):
        img = base_img_circles.copy()
        circles = detector(value)
        draw_hough_circles(img, circles, outer_color, center_color)

        label_text = label_text_fn(value)
        label_file = label_file_fn(value)
        cv2.imwrite(f'{output_dir}/{file_prefix}_{label_file}.png', img)
        axes[idx].imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        axes[idx].set_title(f'{parameter_name} = {label_text}')
        axes[idx].axis('off')

    plt.suptitle(title, fontsize=14)
    plt.tight_layout()
    plt.savefig(f'{output_dir}/{file_prefix}_grid.png', dpi=200, bbox_inches='tight')
    plt.show()

dp_values = [1.0, 1.2, 1.5]
minDist_values = [10, 20, 40]
param1_values = [40, 60, 100]
param2_values = [30, 60, 90]
minRadius_values = [10, 20, 35]
maxRadius_values = [90, 140, 180]

dp_base = 1.0
minDist_base = 20
param1_base = 60
param2_base = 60
minRadius_base = 20
maxRadius_base = 140

gridtest_hough_circles(
    dp_values,
    lambda dp: cv2.HoughCircles(
        gray_circles, cv2.HOUGH_GRADIENT, dp, minDist_base,
        param1=param1_base, param2=param2_base,
        minRadius=minRadius_base, maxRadius=maxRadius_base
    ),
    'Variasi Parameter dp - Hough Circles',
    'hough_circles_dp',
    'dp',
    label_text_fn=lambda value: f'{value:.1f}',
    label_file_fn=lambda value: f'{value:.1f}'.replace('.', '_'),
)

gridtest_hough_circles(
    minDist_values,
    lambda minDist: cv2.HoughCircles(
        gray_circles, cv2.HOUGH_GRADIENT, dp_base, minDist,
        param1=param1_base, param2=param2_base,
        minRadius=minRadius_base, maxRadius=maxRadius_base
    ),
    'Variasi Parameter minDist - Hough Circles',
    'hough_circles_minDist',
    'minDist',
)

gridtest_hough_circles(
    param1_values,
    lambda param1: cv2.HoughCircles(
        gray_circles, cv2.HOUGH_GRADIENT, dp_base, minDist_base,
        param1=param1, param2=param2_base,
        minRadius=minRadius_base, maxRadius=maxRadius_base
    ),
    'Variasi Parameter param1 - Hough Circles',
    'hough_circles_param1',
    'param1',
)

gridtest_hough_circles(
    param2_values,
    lambda param2: cv2.HoughCircles(
        gray_circles, cv2.HOUGH_GRADIENT, dp_base, minDist_base,
        param1=param1_base, param2=param2,
        minRadius=minRadius_base, maxRadius=maxRadius_base
    ),
    'Variasi Parameter param2 - Hough Circles',
    'hough_circles_param2',
    'param2',
)

gridtest_hough_circles(
    minRadius_values,
    lambda minRadius: cv2.HoughCircles(
        gray_circles, cv2.HOUGH_GRADIENT, dp_base, minDist_base,
        param1=param1_base, param2=param2_base,
        minRadius=minRadius, maxRadius=maxRadius_base
    ),
    'Variasi Parameter minRadius - Hough Circles',
    'hough_circles_minRadius',
    'minRadius',
)

gridtest_hough_circles(
    maxRadius_values,
    lambda maxRadius: cv2.HoughCircles(
        gray_circles, cv2.HOUGH_GRADIENT, dp_base, minDist_base,
        param1=param1_base, param2=param2_base,
        minRadius=minRadius_base, maxRadius=maxRadius
    ),
    'Variasi Parameter maxRadius - Hough Circles',
    'hough_circles_maxRadius',
    'maxRadius',
)